### ISSUE TITLE
How does one select own theme?

### ISSUE THREAD

**Issue by noudadrichem** [rossriley/docker-bolt#4]
I'm unable to select my own theme:

file setup:
```.
├── app
│   ├── cache
│   ├── config
│   │   ├── extensions
│   │   │   └── menu_backups
│   │   └── files
│   └── database
├── db-data
├── extensions
│   └── vendor
│       ├── bolt
│       │   ├── jsonapi
│       │   │   ├── config
│       │   │   └── src
│       │   │       ├── Action
│       │   │       ├── Config
│       │   │       ├── Controllers
│       │   │       ├── Converter
│       │   │       │   └── Parameter
│       │   │       │       └── Type
│       │   │       ├── Exception
│       │   │       ├── Helpers
│       │   │       ├── Parser
│       │   │       │   └── Field
│       │   │       │       └── Type
│       │   │       ├── Provider
│       │   │       ├── Response
│       │   │       └── Storage
│       │   │           └── Query
│       │   │               └── Handler
│       │   │                   └── Directive
│       │   └── theme-2016
│       │       ├── css
│       │       ├── images
│       │       ├── js
│       │       ├── partials
│       │       ├── screenshots
│       │       ├── source
│       │       │   ├── javascript
│       │       │   ├── scss
│       │       │   └── wireframes
│       │       └── wireframes
│       └── composer
└── public_html
    ├── bolt-public
    ├── extensions
    ├── files
    ├── theme
    │   └── base-theme-2
    │       ├── blocks
    │       ├── components
    │       │   └── menus
    │       ├── css
    │       │   ├── bootstrap
    │       │   │   ├── mixins
    │       │   │   └── utilities
    │       │   ├── components
    │       │   │   └── blocks
    │       │   ├── public
    │       │   └── utilities
    │       ├── font-awesome
    │       │   ├── css
    │       │   └── js
    │       ├── fonts
    │       │   ├── Belgrano
    │       │   ├── Mina
    │       │   └── Source_Sans_Pro
    │       ├── forms
    │       ├── fullcalendar-3.9.0
    │       │   ├── demos
    │       │   │   ├── js
    │       │   │   ├── json
    │       │   │   └── php
    │       │   ├── lib
    │       │   └── locale
    │       ├── js
    │       └── media
    │           └── favicon
    └── thumbs

```

Docker-compose.yml
```
version: '2'

services:
    bolt:
        image: rossriley/docker-bolt:3.4
        network_mode: bridge
        environment:
            - BOLT_TITLE=Indicium
            - BOLT_THEME=./public_html/theme/base-theme-2
        volumes:
            - ./db-data:/var/www/html/app/database
            - ./public_html:/var/www/html/public/files
            - ./extensions:/var/www/html/extensions
        ports:
          - 80:80
```
